### PR TITLE
Connectivity handling

### LINKED ISSUE #22: Going offline crashed realtime updates and eventually the app.

### LINKED ISSUE #104: Unhandled Promise Rejection Popups when open a long time
Getting Unhandled Promise rejection popups in the following scenarios

- Leaving wallet open for a long time
- Network connectivity changes

Also when internet connection drops, unable to reload wallet after reconnection, gets stuck on contacting network message

### PR DESCRIPTION
**Pull request by gabmontes**
Captures several unhandled exceptions, sends cached information when available and splits transaction parsing code in there own files for clarity.

As yapa, it adds a `contractCallFailed` flag to the transaction meta properties to help identifying transactions with failed contract execution calls.

Resolves #22 
Resolves #104

### CODE REVIEW

File: public/main/tokens/settings.js [hunk 1]
```diff
@@ -10,4 +11,24 @@ function getTokenSymbol (address) {
   return settings.get(`tokens.${address.toLowerCase()}.symbol`)
 }
 
-module.exports = { getTokenContractAddresses, getTokenSymbol }
+function setTokenBalance ({ walletId, address, contractAddresse, balance }) {
```
Comment (pablen) [inline public/main/tokens/settings.js]: I'm worried for this typo to come and haunt us in the future.

**Review by ianaya89 — APPROVED** [review]
💯

**Review by pablen — APPROVED** [review]
